services:
  ia_communicate:
    hostname:         ia_communicate.innovanon.com
    build:
      context:        .
      tags:
        - innovanon/ia_communicate:latest
        -           ia_communicate:latest
        - innovanon/ia_communicate
        -           ia_communicate
    restart:          no
    logging:
      driver:         syslog   
